name: Cryptarithm-Solver-Web
services:
  redis:
    container_name: redis
    image: redis:7.4.0-alpine
    volumes:
      - redis:/data
    networks:
      - cryptarithm
    command: "redis-server --maxmemory 100mb --maxmemory-policy allkeys-lfu"
    restart: unless-stopped

  server:
    container_name: server
    build:
      context: ./server
    depends_on:
      - redis
    env_file:
      - ./server/.env
    environment:
      - HOST=0.0.0.0
    networks:
      - cryptarithm
    restart: unless-stopped

  client:
    container_name: client
    build:
      context: ./client
    depends_on:
      - server
    networks:
      - cryptarithm
    restart: unless-stopped

  proxy:
    container_name: proxy
    build:
      context: ./proxy
    depends_on:
      - client
    networks:
      - cryptarithm
    ports:
      - 8080:80
    restart: unless-stopped

volumes:
  redis:

networks:
  cryptarithm:
