name: Cryptarithm-Solver
services:
  redis:
    container_name: redis
    image: redis:7.4.0-alpine
    volumes:
      - redis:/data
    networks:
      - cryptarithm-network
    command: "redis-server --maxmemory 100mb --maxmemory-policy allkeys-lfu"
    # restart: always

  server:
    container_name: server
    env_file: ./server/.env
    build:
      context: ./server
    depends_on:
      - redis
    networks:
      - cryptarithm-network
    ports:
      - 3000:3000
    # restart: always

  client:
    container_name: client
    env_file: ./client/.env
    build:
      context: ./client
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL:-http://127.0.0.1:3000/api}
    networks:
      - cryptarithm-network
    ports:
      - 8080:80
    # restart: always

volumes:
  redis:

networks:
  cryptarithm-network:
