FROM node:22-alpine

# Create and set working directory
WORKDIR /usr/src/app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm ci

# Copy the rest of the application code
COPY . .

# Expose the port and start the application
EXPOSE 3001
CMD ["npm", "start"]
